version: '3.9'

services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app/app
      - ./common:/app/common
      - ./server:/app/server
      - ./tests:/app/tests
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    command: sh -c "uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DB_HOST=db
      - CACHE_HOST=cache
      - DEBUG=true
    # depends_on:
    #   - db
  
  # docs:
  #   build:
  #     context: .
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 8001:8001
  #   command: sh -c "mkdocs serve -a 0.0.0.0:8001"

  # db:
  #   image: postgres:13-alpine
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data
  #   env_file:
  #     - ./.env.dev

  # db:
  #   image: mongo:7.0
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #     - mongo_data:/data/db
  #     - mongo_log:/var/log/mongodb
  #   env_file:
  #     - ./.env.dev
  #   command: [--auth]

# volumes:
  # mongo_data:
  # mongo_log:
